Add git user info in local.conf as a workaround to pass ci build
@Description/root cause - Why
After upgrading to yocto scarthgap version,
git related errors occurred when applying patch during compilation:
ERROR: optee-os-tadevkit-4.5.0-r0 do_patch: Applying patch 'xxx' on target directory 'xxx'
CmdError("git notes --ref refs/notes/devtool append -m 'original patch: xxx' HEAD", 0, 'stdout:
stderr: Author identity unknown

Solution 1: modify the local.conf to export the git user information
Solution 2: modify the crops docker to add git user info in ~/.gitconfig

In order to unblock CI build, use Solution 1 as workaround now.

@Resolution - How
export git user information in local.conf
Add param BB_ENV_PASSTHROUGH_ADDITIONS to append environment variables containing git user information

Change-Id: I4729cb644fee64d2d2a2d47e8fef7cfc7da81028
Reviewed-on: https://gerrit-sha.synaptics.com/gerrit/262829
Reviewed-by: Tao Yu <Tao.Yu@synaptics.com>