security: add SRCREV_FORMAT for tee to fix CD build issue
bb.data_smart.ExpansionError: Failure expanding variable fetcher_hashes_dummyfunc[vardepvalue], expression was ${@bb.fetch.get_hashvalue(d)} which triggered exception FetchError: Fetcher failure: The SRCREV_FORMAT variable must be set when multiple SCMs are used.
The SCMs are:
git://git.trustedfirmware.org/TF-A/trusted-firmware-a.git;protocol=http;branch=master
git://git@github.com/syna-astra-stage/tee;protocol=ssh;branch=scarthgap_6.12_v2.0.1.2-202510161911-202510170021;destsuffix=git/tee;name=tee
The variable dependency chain for the failure is: fetcher_hashes_dummyfunc[vardepvalue]

ERROR: Parsing halted due to errors, see error messages above
Change-Id: I5a19d32b59c2b060f4a8cd5b3d4e50421d1b03ab
Signed-off-by: Jingju Hou <Jingju.Hou@synaptics.com>
Reviewed-on: https://gerrit-sha.synaptics.com/gerrit/278435